name: Build
on:
  push:
    branches:
      - main
jobs:
  flutter:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && startsWith(github.event.pull_request.title, 'Draft') == false
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'
      - name: Download dependencies
        run: flutter pub get
      - name: Setup Supabase
        uses: supabase/setup-cli@v1
      - name: Start Supabase local for tests
        run: supabase start
      - run: flutter test
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "tech+gitbot@parousia.app"
          git fetch origin gh-pages:gh-pages
      - name: Compile web and put in gh-pages branch
        run: dart run peanut --extra-args "--dart-define=ENV=dev"
      - name: Push gh-pages
        run: git push origin gh-pages
      - name: Retrieve the Android keystore and key properties
        env:
          UPLOAD_KEYSTORE_B64: ${{ secrets.UPLOAD_KEYSTORE_B64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          echo "$UPLOAD_KEYSTORE_B64" | base64 --decode > android/keystore.jks
          echo "$KEY_PROPERTIES" > android/key.properties
      - name: Compile Android app
        run: flutter build appbundle --build-number ${{ github.run_number }} --dart-define=ENV=dev
      - name: Upload Android app to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: is.giorgio.app.parousia
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
          mappingFile: build/app/outputs/mapping/release/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/release/out/lib
