name: Verify

on:
  pull_request:
  merge_group:

# We only care about the latest version: stop old jobs if a new commit is pushed.
# The fallback on github.ref is for when the workflow is for a merge queue.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && startsWith(github.event.pull_request.title, 'Draft') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Download dependencies
        run: flutter pub get

      - name: Setup Supabase
        uses: supabase/setup-cli@v1

      - name: Start Supabase local for tests
        run: supabase start

      - name: Run tests
        run: |
          supabase status -o json > supabase/config/localhost.json
          flutter test

      - name: Compile web
        run: flutter build web
